# Generated by Django 3.0.4 on 2020-03-20 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='null', max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(default='iniciado', max_length=200)),
                ('numero_fases', models.IntegerField(default=0)),
                ('cant_comite', models.IntegerField(default=0)),
                ('gerente', models.CharField(default='null', max_length=250)),
                ('comite', models.CharField(default='null', max_length=700)),
                ('participantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=800)),
                ('prefijo', models.CharField(max_length=5)),
                ('proyecto', models.ManyToManyField(to='administracion.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaAtributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('tipo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.TipoItem')),
            ],
        ),
    ]
