# Generated by Django 3.0.4 on 2020-03-22 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioxrol',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuarioxrol',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Fase'),
        ),
        migrations.AddField(
            model_name='usuarioxrol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Rol'),
        ),
        migrations.AddField(
            model_name='tipoitem',
            name='proyecto',
            field=models.ManyToManyField(to='administracion.Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='participantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantillaatributo',
            name='tipo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.TipoItem'),
        ),
        migrations.AddField(
            model_name='fase',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Proyecto'),
        ),
    ]
