# Generated by Django 3.0.4 on 2020-03-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('nombre_y_apellido', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('contrasegna', models.CharField(default='empty', max_length=200)),
                ('lista_permisos_sistema', models.CharField(max_length=800)),
            ],
        ),
    ]
